apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    traffic-type: public
    {{- include "common.labels" . | indent 4 }}
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/custom-response-headers: 'x-frame-options: '
  name: rutedb
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: rutedb.{{ .Values.ingress.domain }}

    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: {{ template "chouette2.name" . }}
              port:
                number: {{ .Values.service.http.externalPort }}
