apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    traffic-type: public
    app: chouette2
    shortname: chouette2
    team: ror
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/custom-response-headers: 'x-frame-options: '
  name: rutedb
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: rutedb.{{ .Values.ingress.domain }}
    http:
      paths:
        - pathType: ImplementationSpecific
          backend:
            service:
              name: chouette2
              port:
                number: {{ .Values.common.service.externalPort }}
