env: tst

sql:
  instance: ent-chouette-tst:europe-west1:chouette-db-pg13=tcp:5432

chouetteUrl: http://chouette.tst.entur.internal
osrmRailUrl: http://osrm-rail.tst.entur.internal
osrmBusUrl: http://osrm-bus.tst.entur.internal
osrmWaterUrl: http://osrm-water.tst.entur.internal

ingress:
  domain: staging.entur.org

